version: '3'

services:
  api:
    container_name: "snippet_manager_api"
    build:
      context: .
      dockerfile: Dockerfile_dev
    ports:
      - 8080:8080
    env_file:
      api.env

  db:
    container_name: "snippet_manager_db"
    image: postgres:12
    ports:
      - 5432:5432
    env_file:
      - db.env
    volumes:
      - snippet-manager:/var/lib/postgresql/data
#  redis:
#    container_name: "redis"
#    image: redis:6-alpine
#    ports:
#      - "6379:6379"

volumes:
  snippet-manager:
    external: true